version: "3.8"
services:
  patient-db:
    image: postgres:15
    container_name: patient-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patientdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - patient-net
  patient-service:
    build:
      context: ./Patient-Service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "8080:8080"
    depends_on:
      - patient-db
    networks:
      - patient-net
volumes:
  pgdata:
networks:
  patient-net:
    driver: bridge
